# Generated by Django 4.2.6 on 2023-10-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='snippet',
            table='snippet',
        ),
    ]
