# Generated by Django 4.2.6 on 2023-11-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_user_tag_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
