# Generated by Django 4.2.6 on 2023-10-30 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_remove_snippet_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
